development:
  adapter: thin
  server: "http://localhost:9292"
  secret_token: "secret"
  mount: '/faye'
test:
  adapter: thin
  server: "http://localhost:9292"
  secret_token: "secret"
  mount: '/faye'
production:
  adapter: thin
  server: "http://faye.example.com"
  mount: '/faye'
  secret_token: "bb3a3c346bc762a25027453cf874bef8b767d5445cdc23cf67ce7242b40dd23f"
  signature_expiration: 3600 # one hour
