connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: pnc
  password: <%= ENV["PG_PASS"] %>

development:
  <<: *connection
  database: spolisty_development

test: &test
  <<: *connection
  database: spolisty_test
